### PR TITLE
Updated talk proposal templates to include first-time speaker indication

### PR DESCRIPTION
**Pull request by carolstran**
Added a way that people can indicate whether this will be their first tech talk to the issue template since we always end up asking anyway ✨

### CODE REVIEW

**Review by rmehner — APPROVED** [review]

**Comment by carolstran** [comment]
@rmehner @Mohamed3on Trying to decide if this kind of information would be better in the name section or in the abstract section (aka why I made a pr)... wdyt? 🤔

**Comment by rmehner** [comment]
Hard to say, but leaning towards name, because if it's in the abstract section it might be misunderstood as "This is the first time I'm giving **this** talk" vs. "This is the first time **I** give a tech talk".

**Review by rmehner — APPROVED** [review]

**Comment by Mohamed3on** [comment]
Name sounds good! :shipit:

**Review by Mohamed3on — APPROVED** [review]

**Comment by carolstran** [comment]
Yay danke @rmehner and @Mohamed3on 😊 😊 😊

**Pull request merged**
