### PR TITLE
Throw in some Jekyll for rendering BerlinJS site

### PR DESCRIPTION
**Pull request by localheinz**
This PR
- adds configuration to compile the site with Jekyll and Markdown
- extracts a layout for BerlinJS pages
- extracts templates for meetups and empty slots
- allows for rendering talks with Markdown

### CODE REVIEW

**Comment by parkr** [comment]
:+1: :wolf:

**Comment by localheinz** [comment]
@rmehner 

Unsure if I should use push permissions already to merge this in. What do you think?

**Comment by rmehner** [comment]
I'll review it this weekend and then we can go on :) Sorry for slowing down the process a bit, but:

**Comment by localheinz** [comment]
No worries!

**Comment by rmehner** [comment]
Finally had the chance to looking through it. Nice & clean, code wise there is only one thing I'm not too sure of: Sometimes we have meetups with more than 3 talks and the iterator is not suited for that case. But I guess that's easy to fix (even though the modulus module in Jekyll didn't work too well until recently).

A much bigger problem, which is not caused by you, but by using Jekyll is the following: so far we had the following relatively easy workflow for talk submissions which works the same on every platform:
- fork & clone the repo
- open the index.html and edit it to your needs
- refresh the browser to see how it looks
- commit, push, open PR

With using Jekyll this changes to:
- fork & clone the repo
- get the Ruby / Rubygems / Jekyll setup on your machine, which is a task of varying difficulty and might lead to grey hairs ;)
- start jekyll
- open the _data/meetups.yml and edit it to your needs
- refresh the browser to see how it looks
- commit, push, open PR

If I see this correctly, a talk proposal would be a pull request on _data/meetups.yml looking something like that:

``` patch
diff --git a/_data/meetups.yml b/_data/meetups.yml
index f709f32..ea2066d 100644
--- a/_data/meetups.yml
+++ b/_data/meetups.yml
@@ -9,6 +9,13 @@

 - time: 2014-01-16 19:00:00 +0100
   talks:
+    - |
+      ### My talk title
+      ##### [Someone's speaking](https://twitter.com/berlinjs)
+
+      I'm gonna talk about stuff
+
+      Way longer description

 - time: 2013-11-21 19:00:00 +0100
   talks:
```

which is so far no big problem, only that it might be way to easy to break it (forgetting the `|` in the beginning for example).

This is way more complex for anyone who's interested in giving a talk. BerlinJS should make it easy for people to submit and give talks.

We might be able to simplify the format a bit by having a key / value setup (think title: "foo" in the yml) but that only eases the input, not the preview part. Maybe even a separate Markdown file per talk in a meetup folder or something like that.

So yeah, I really like this Jekyll thing, as this makes it easier for us, I'm just not sure if it's the right way to go for receiving talk submissions as I'm not sure how vital that "preview my change in the browser" part is. Maybe we can find another simple way to have talk submissions?

@janl @theophani, what do you think about that?

@localheinz thank you so much for taking your time and going outside your comfort zone to make this Pull Request. Very much appreciated! :)

**Comment by localheinz** [comment]
@rmehner 

Thank you very much for your detailed feedback, I appreciate it.

Also I agree that the barrier to submit an entry is a bit a high and error-prone. 

In the light of https://github.com/berlinjs/new-berlinjs.org/pull/4 we'll have the same problem though. Maybe there's a better solution. I'll try to come up with something that's simpler.

**Comment by localheinz** [comment]
Maybe there's a way of making each talk a post of a certain category (e.g., `talk`) and then iterating over the posts for a certain date to render talks for a meetup. 

Then an interested speaker would only have to add a post in HTML format.

I'll investigate!

**Comment by rmehner** [comment]
On 16.12.2013, at 19:00, Andreas Möller notifications@github.com wrote:

> @rmehner
> 
> Thank you very much for your detailed feedback, I appreciate it.
> 
> Also I agree that the barrier to submit an entry is a bit a high and error-prone.
> 
> In the light of berlinjs/new-berlinjs.org#4 we'll have the same problem though. Maybe there's a better solution. I'll try to come up with something that's simpler.

As I said, it's not your solution that is wrong but the general approach. We should think about what we want to have as best talk submission solution. I want something that has nearly no barrier for someone who wants to give a talk. It should be encouraging and so easy that everyone can get on stage :)

**Pull request closed without merging**
