### PR TITLE
Lindsay's talk proposal for BerlinJS 17.04.2014

### PR DESCRIPTION
**Pull request by leyink**
Coming in a bit late. I mentally checked this off my todo list. Hopefully you guys like the idea and it's not too late! Def not a tech talk. This is a similar talk to one I gave at AltTechTalks Berlin in December 2013. Feedback welcome and appreciated. :)

Know Your Roots
@leyink
A brief history of the tech industry and Silicon Valley &mdash; LSD, counterculture, hippies, communes, The Whole Earth Catalog, and California.

History and culture inform everything we do. Where you grew up affects how you think, the way you create, and how you do business. Should Berlin try to replicate Silicon Valley?

### CODE REVIEW

**Comment by janl** [comment]
I invited @leyink to submit this one as I believe it is a really important topic that isn’t talked enough about in our circles :)

**Comment by janl** [comment]
Got a private +1 from @rmehner :)

**Comment by rmehner** [comment]
Thank you for proposing the talk and see you tomorrow. Looking forward.

**Comment by leyink** [comment]
Awesome, thanks for having me. <3

**Pull request merged**
