### PR TITLE
Add proposal for meetup/april "One Year Of Fun As AngularJS Consultant"

### PR DESCRIPTION
**Pull request by robinboehm**

### CODE REVIEW

**Comment by robinboehm** [comment]
Too much todo, no time to prepare the talk.
Will join the meetup as guest.

**Comment by rmehner** [comment]
Argh, too bad. Would have loved to hear you. Anyway, looking forward to meeting you at our meetup :)

**Comment by localheinz** [comment]
@rmehner @robinboehm 

Sounds like https://github.com/berlinjs/berlinjs.org/pull/117#issuecomment-39738911 is actually a summary of the talk already?

:trollface:

**Comment by robinboehm** [comment]
@localheinz Hell Yeah -> Yes !! ;)

**Pull request closed without merging**
