### PR TITLE
Talk proposal: the Acorn JavaScript parser

### PR DESCRIPTION
**Pull request by marijnh**
It's been sooooo long since I've bored the good people at the Berlin JS usergroup.

### CODE REVIEW

**Comment by NV** [comment]
As a parser entusiasto, I’d love to hear the talk!

**Comment by marijnh** [comment]
@rmehner: What's up? I see another talk got added. Does that mean this one is being rejected?

**Comment by theophani** [comment]
Not rejected, just delayed as he is from out of town, but you can come in the future (January?) instead.

**Comment by NV** [comment]
I assume you were talking about me. I could shrink my talk from 30 to 15 minutes if it helps.

**Comment by theophani** [comment]
We've been talking out of band about limiting the upcoming meetup to 4 talks. Yes, @NV, you were the person we've talking about having as the 4th talk this time around.

@marijnh: How long would your talk be? Since your most vocal +1 is also the person taking your spot, it perhaps makes sense to try and fit you in after all :)

(ps: I'm also super excited to hear about Acorn too – but I'm out of town for the meeting this month)

**Comment by marijnh** [comment]
I'm perfectly okay with postponing the talk! I was just a bit surprised about the complete lack of communication.

**Comment by theophani** [comment]
Sorry about that! We only discussed it super late last night and had not actually got around to asking / telling you yet. Sowwy!

**Comment by rmehner** [comment]
Sorry @marijnh, as Tiffany said we discussed this late yesterday and I was very sick the weeks before and didn't manage to work off my gigantic backlog completely yet.

Sorry again.

**Comment by marijnh** [comment]
No problem at all! Hope you're feeling better.

**Comment by rmehner** [comment]
Alright, I put your talk into the list for January. Thank you very much again for your understanding and being an active part of the community!

**Comment by rmehner** [comment]
@marijnh is your proposal still valid for our next meetup on January 17th? If so I'll merge it. Thank you :)

**Comment by marijnh** [comment]
Yes, still valid. By all means, do merge it!

**Pull request merged**
