### PR TITLE
Upgrading to Webpack 2

### PR DESCRIPTION
**Pull request by felixjung**
Hi,

I recently upgraded our Angular 1.5 app at work from using Webpack 1 to Webpack 2. This involved things like 

* optimizing our common chunk setup,
* ensuring we use member imports for some popular libraries like D3,
* introducing the lodash Babel plugin,
* making some more changes to the config to benefit from tree-shaking and dead code elimination.

To monitor my progress, I used the Webpack Bundle Analyzer to see how the code chunks and overall code size developed.

I don't have slides for this, yet, but I would like to share some of my experience with the upgrade process.

### CODE REVIEW

**Comment by felixjung** [comment]
Sorry, but you haven't responded all weekend and I will need some more time to prepare. Maybe next Meetup.

**Comment by rmehner** [comment]
Hey, sorry, decided to have a slow weekend :)

Anyway, your talk sounds super interesting and we would love to have you in March then. I'll note you down so we don't forget about you.

Also, if you need any help with your talk, feel free to ping us.

**Comment by felixjung** [comment]
Hey @rmehner, sweet! Thanks.

**Comment by rmehner** [comment]
Hey there, are you still on for March?

**Comment by rmehner** [comment]
ping @felixjung :) Are you still up for March?

(don't worry about the merge conflicts, I can deal with that)

**Comment by rmehner** [comment]
According to Twitter you're up for it so I've merged this :)

**Comment by felixjung** [comment]
Sweet 👍

**Comment by felixjung** [comment]
Have to make some changes, though. Description is a bit outdated.

**Comment by rmehner** [comment]
Sure thing, just send a PR with those changes :)

**Pull request merged**
