### PR TITLE
Propose React+Flux talk

### PR DESCRIPTION
**Pull request by gaearon**
I gave this talk in Russia previously with [these slides](http://slides.com/danabramov/components-react-flux-wip). It was much longer so I'll have to be dense. Please let me know if it's better to focus on intro or advanced concepts!

### CODE REVIEW

**Comment by rmehner** [comment]
Thank you :) I'll point the community to this PR and let them answer right here.

**Comment by janmonschke** [comment]
An introduction would be cool :smiley:

**Comment by xMartin** [comment]
Would love to have some advanced architecture scenarios.

**Comment by optikfluffel** [comment]
:+1: for advanced concepts

**Pull request merged**
