### PR TITLE
Talk submission 2FA, WTF

### PR DESCRIPTION
**Pull request by dkundel**

### CODE REVIEW

**Comment by rmehner** [comment]
Hey Dominik, would you be up for giving this talk in June as well? We have someone who pinged us on @berlinjs last month already for a spot :)

**Comment by dkundel** [comment]
Would that be June 16?

**Comment by rmehner** [comment]
Exactly, it's always on the third Thursday of the month.

**Comment by dkundel** [comment]
Jep that would work!

**Comment by dkundel** [comment]
Is this still on? :)

**Comment by rmehner** [comment]
Hey @dkundel,

we thought about only having two talks this Thursday (#202 being the other one), since there is this Germany Euro Cup game that many people want to see. Would September (we're doing a summer break after this month' meetup) work for you? Sorry for the very late notice, I've been travelling and didn't check my emails too often.

**Comment by dkundel** [comment]
Hey Robin,

Would have preferred June but if you already confirmed the other two I can try to do it in September.

Cheers,
Dominik

**Comment by sheley** [comment]
@dkundel I just sent you a message from the berlinjs account on twitter, just pinging you here in case you see this first. One of our speakers fell ill and if you'd like to take the spot we'd be happy to have you!

**Pull request closed without merging**
