### PR TITLE
Added information about wooga's talk

### PR DESCRIPTION
**Pull request by hdragomir**

### CODE REVIEW

**Comment by janl** [comment]
Not to be all picky, but how would you feel about making it a little more personal?

specifically, list your twitter account and your name instead of "someone from wooga"? :)

**Comment by hdragomir** [comment]
I know, I know -- but I'm not sure if it will be me or my colleague, Florian.

Maybe keep it as it is until we know for sure?

**Comment by janl** [comment]
Sure :)

**Comment by hdragomir** [comment]
Oh, I meant keep it as an open pull request... Thankies.

**Comment by janl** [comment]
Nah, we'll just fix it later :)

**Pull request merged**
