### PR TITLE
Website update for beer.js

### PR DESCRIPTION
**Pull request by veganben**
Faded the speaker bits, added a berlin.js bit and some text. 
Also added in the missing title attributes for anchors

### CODE REVIEW

**Comment by veganben** [comment]
The red on beer.js is far too red. You might want to swap it to 
    color: #df2f58;
(styles.css, line 521)
Sorry. Was lazy and forgot to do it. Didn't think it was worth another pull request for that one line.

**Comment by janl** [comment]
You can update your bench with the change and the PR will auto update.

**Comment by veganben** [comment]
issatso? It's like magic n stuff.  Done :)

**Comment by rmehner** [comment]
Merged.

**Comment by bkw** [comment]
Congrats on your first pr, @veganben!

**Pull request merged**
