### PR TITLE
Talk proposal: url-io - What the world looks like as observable paths

### PR DESCRIPTION
**Pull request by liamcmitchell**
I want to share <a href="https://github.com/liamcmitchell/url-io">url-io</a>, a library I have developed over the last few years to manage data fetching.

URLs (or at least paths) are very well understood. By resolving these paths with Observables (RxJS), we can build reactive applications by defining our data dependencies as paths.

### CODE REVIEW

**Comment by rmehner** [comment]
Hey there,

going through our backlog I've noticed this talk and just saw that we never got back to you. Sorry!

Are you based in Berlin? Looks like we're full for July and September, what other months would work for you?

**Comment by liamcmitchell** [comment]
Hi, no worries.
Yes, I'm in Berlin. Any time should be fine as long as I know the date in advance.

**Comment by carolstran** [comment]
Hey @liamcmitchell, sorry again for the massive delay in response 🙈 I was wondering if you would still be interested in giving this talk. And if so, how long would it be? It would also be great to know if you're a first-time speaker or if you've given talks like this before. 

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by carolstran** [comment]
👋 @liamcmitchell, just checking in on this to see if you're still interested in speaking. If you don't reply within a week or so then I'll close the PR (mostly to keep everything organized) - but of course, you can always open a new one 😁

**Comment by liamcmitchell** [comment]
Hi, thanks for asking. I'm still interested. I have never given this as a talk before so I'm not sure how long it needs.

**Comment by carolstran** [comment]
Great @liamcmitchell! Do you have any months that work particularly well (or don't work) for you in Q2/Q3?

**Comment by liamcmitchell** [comment]
No preference at this point

**Comment by carolstran** [comment]
Alright, what about during Q2 (we have spots in both April and May) or would you prefer later in the year, more Q3 or Q4?

**Comment by liamcmitchell** [comment]
Sorry for ignoring you. I'm a terrible procrastinator. I would be happy to do it as soon as you have time for me. I just need a date set so I can prepare.

And thanks for making your meetup so welcoming. It makes this easier :)

**Comment by carolstran** [comment]
I'm clearly also a terrible procrastinator, so I take no offense 😄 Let me double check with my fellow organizers and get back to you. As of now, I know that any month in Q3 is open if any of those sound especially good to you.

**Comment by carolstran** [comment]
Also thank you for the nice words about our meetup 💕 💕 💕

**Comment by liamcmitchell** [comment]
Great, put me in the first one. I don't think I have anything in the way

**Comment by carolstran** [comment]
Awesome! That would be on Thursday, July 18. I'll put you down and just feel free to reach out again if that ends up not working for you 😊

**Comment by carolstran** [comment]
Hey @liamcmitchell, just wanted to check in to see if you're still up for presenting in July! If not no problem, we can find another time - just let us know either way please 😇

**Comment by liamcmitchell** [comment]
Yes, still up for it. Thanks

Carolyn Stransky <notifications@github.com> schrieb am Sa., 22. Juni 2019,
23:27:

**Comment by carolstran** [comment]
Hey @liamcmitchell! Here's the updated website, let us know if you'd like us to change anything about your info or abstract (I changed "I" to your name but I can change it back if you want): https://berlinjs.org/

We'll be announcing speakers on Twitter tomorrow 🛰

**Comment by carolstran** [comment]
Hey hey @liamcmitchell, really looking forward to meeting you and hearing your talk 🎉 

FYI we added a fourth speaker for tonight so here is the tentative schedule...

⚡️ Jan-Niklas
🎤 You!
- break - 
⚡️ Łukasz
🎤 Robin

I'll be the only organizer there tonight, so just find me before and we can do a quick tech check 😊

**Comment by liamcmitchell** [comment]
Thanks! See you soon

**Comment by carolstran** [comment]
Thanks again @liamcmitchell, tonight was excellent 💖 If you share your slides somewhere (no pressure), let me know and I can tweet it from the BerlinJS account 😁

**Comment by carolstran** [comment]
Oh and closing this PR now 🎉

**Pull request closed without merging**
