### PR TITLE
Talk proposal: Chrome DevTools

### PR DESCRIPTION
**Pull request by NV**
Going to Berlin, would love to give a talk.

### CODE REVIEW

**Comment by rmehner** [comment]
Looks good. How long will this talk be? And do you have a little bit more info to put into the abstract?

**Comment by NV** [comment]
30 minutes. Last week I gave one hour talk at MoscowJS. Not sure I can do the same in English :)

**Comment by rmehner** [comment]
Our talks are usually around 20 minutes. Maybe try to get the important things over in 20 minutes and then see how Q&A evolves and have some slides as backup :)

Will merge this into the site asap.

Thank you!

**Comment by rmehner** [comment]
Merged in 365083b0088fff612213b02297bba4275564e278

**Pull request closed without merging**
