### PR TITLE
Add talk "Crafting lovely git narratives to enable software archaeology"

### PR DESCRIPTION
**Pull request by mroderick**

### CODE REVIEW

**Comment by rmehner** [comment]
Hey there, would you be able to give that talk in March as well?

**Comment by mroderick** [comment]
Absolutely

**Comment by rmehner** [comment]
Alright, then I'll plan you in for March and we'll have #215 for February. Thanks Morgan! :)

**Comment by mroderick** [comment]
Great!

**Comment by rmehner** [comment]
Welcome to our March lineup :)

**Comment by mroderick** [comment]
> Welcome to our March lineup :)

I better finish my slides then ;)

**Pull request merged**
