### PR TITLE
Pull Request for Thom Bradford's talk "Why a JavaScript Query Language?"

### PR DESCRIPTION
**Pull request by kode4food**
**NOTE**: I am proposing this talk for the October meeting.  There's a chance I'll be out of town on the 20th, otherwise I'd propose it for the September meeting.

### CODE REVIEW

**Comment by rmehner** [comment]
Perfect. So just hit us up as soon as you know if you're out of town or not so we can merge accordingly.

Thank you very much.

**Comment by kode4food** [comment]
Okay, I should know for sure in the next couple of days.

**Comment by kode4food** [comment]
Ok, looks like I _will_ be available to present for the September 20th meeting.

**Comment by rmehner** [comment]
Yeah! Thank you.

**Pull request merged**
