### PR TITLE
Talk proposal: Delivering Applications with Electron

### PR DESCRIPTION
**Pull request by salomvary**
This is meant to be a full 25 minutes long talk.

### CODE REVIEW

**Comment by theophani** [comment]
👍 

I'm not an official organizer anymore, but I vote yes!

**Comment by rmehner** [comment]
Very interesting indeed, thanks for submitting. Just a quick heads up: This would be for January, as there is no December meetup. Okay?

**Comment by salomvary** [comment]
>  This would be for January, as there is no December meetup.

Yup, I'm aware of that.

**Comment by rmehner** [comment]
Well then, welcome aboard :)

**Comment by salomvary** [comment]
Thanks :)

**Pull request merged**
