### PR TITLE
sqwiggle talk

### PR DESCRIPTION
**Pull request by awsmsrc**

### CODE REVIEW

**Comment by rmehner** [comment]
Thanks, merged :)

I removed the hiring notice, as we don't have that on our site (because literally everyone is hiring and this would take a lot of space up on the website / the meetup and we want to keep it community :)

That being said our policy is as follows: If you give a talk you're more than welcome to have a slide that says that you're hiring and of course you can tell attendees about that then :)

Looking forward to this "talk from the trenches"!

**Comment by awsmsrc** [comment]
Hi Robin,

No problem! 

I discussed it with Jan and it won’t be a long or in depth talk. 

Casual with discussion encouraged if thats cool?

Sqwiggle do some cool stuff and we aim on open sourcing a lot of stuff to do with WebRTC. So we really want the best of the best to see what we are doing and get involved.

Thanks

**Comment by rmehner** [comment]
Hey Luke,

discussions are always welcome. No worries about the length, we just don't want to have the typical pitch talk as you might have guessed. If you sprinkle the whole thing with code and technical details and maybe problems you've run into, everything is fine :)

**Comment by awsmsrc** [comment]
Hi Robin,

Nah its not a pitch. 
Im just a developer and just want to work with awesome people around the world!
PS just read your blog. Love your tech stack choices! 

Really looking forward to meeting you!

**Pull request merged**
