### PR TITLE
Talk Submission: "Feel the Glimmer"

### PR DESCRIPTION
**Pull request by marcoow**
I can't make it on Sep 21st actually but maybe this is an interesting topic for another date.

### CODE REVIEW

**Comment by rmehner** [comment]
> but maybe this is an interesting topic for another date.

Definitely is. Our meetup is on every third Thursday of the month. What would be the best date for you?

Thanks for the submission, looking forward to learn more about Glimmer :)

**Comment by marcoow** [comment]
I could do Oct. 19th (if I have counted correctly). That's also one week after EmberFest (http://emberfest.eu) so everyone's excitement for Ember and Glimmer might still be fresh ;)

**Comment by rmehner** [comment]
> I could do Oct. 19th (if I have counted correctly). That's also one week after EmberFest (http://emberfest.eu) so everyone's excitement for Ember and Glimmer might still be fresh ;)

Yep, that's the right date. I'll note you down for that date and will get back to you early enough to confirm :)

**Comment by marcoow** [comment]
Nice, looking forward!

**Comment by marcoow** [comment]
I won't be able to make it at the 19th 😞 Maybe we can move it November?

**Comment by rmehner** [comment]
Sure thing :) I'll note you down for November. Have a great weekend!

**Comment by marcoow** [comment]
> Have a great weekend!

You too, thanks!

**Comment by marcoow** [comment]
@rmehner: will have to postpone this again 😔 Jan/18 should certainly work though!

**Comment by verpixelt** [comment]
@marcoow no worries! We'll close this PR then. If January works for you please add a comment to the `January: Call for Speakers` issue once it's open (should be visible at some point in December).

**Pull request closed without merging**
