### PR TITLE
Add a proposal about AlloyEditor

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by rmehner** [comment]
Hey there,

sorry for the late reply, but February was planned to have this React/React-Native special we've talked about during our January meetup (and which has been planned since end of last year). Would you be open to give this talk in March?

**Comment by ipeychev** [comment]
Hello,

Yes, sure!

Thanks,

**Comment by rmehner** [comment]
Hey, does March 17th still work for you? If so, I'd merge this and put you on the page :)

**Comment by ipeychev** [comment]
Hey @rmehner,

Yes, it does!

Thanks,

**Comment by ipeychev** [comment]
@rmehner How much time will be the talk?

Thanks,

**Comment by rmehner** [comment]
See https://github.com/berlinjs/berlinjs.org#how-long-should-my-talk-be :)

**Comment by ipeychev** [comment]
Okay, great!

Thanks,

**Pull request merged**
