### PR TITLE
Talk proposal: tensorflow.js - having fun with machine learning in the browser

### PR DESCRIPTION
**Pull request by fellhorn**
Hello everyone :)
This is Frederic (https://github.com/Langhalsdino) and me from understand.ai
An ML startup for semi automated image annotation from Karlsruhe.
We would like to show you how much fun it is to do some machine learning in the browser and talk with you about the exiting projects you can create, if just anyone can play with your models right in the browser.

Since it would be our very first time @ berlin.js we are really looking forward to getting some input from your site. We already did that talk at OpenCodes hackathon and will do it at the Karlsruhe.js meetup. But every community is different - so we are looking forward to hear what you are interested in!

### CODE REVIEW

**Comment by rmehner** [comment]
👋 

Sorry for the late response, we're in the process of optimising our talk pipeline and it's still a bit rough around the edges :)

Are you going to be in Berlin next week?

**Comment by fellhorn** [comment]
As we saw that there is no slot this time we changed our plans. Maybe there is some slot at an upcoming meetup?

You changed to issues, right?

**Comment by rmehner** [comment]
> Maybe there is some slot at an upcoming meetup?

There sure is. How does June 21st sound for you?

> You changed to issues, right?

That's the canonical way, yes. But there's plenty of other ways as well. We do have an internal waitlist (which is a fancy word for a Trello board we orgas share) where we have all submitted talks collected. We now try to slot them into our available meetups to confirm to speakers early on :)

**Comment by carolstran** [comment]
Hey @fellhorn, sorry again for the massive delay in response 🙈 I was wondering if you would still be interested in giving this talk. And if so, how long would it be? It would also be great to know if you're a first-time speaker or if you've given talks like this before.

I can't guarantee anything at the moment, but we're trying to figure out what we're working with in 2019 and a better way to structure our proposal process in the future 😊

**Comment by carolstran** [comment]
👋 @fellhorn, just checking in on this to see if you're still interested in speaking. If you don't reply within a week or so then I'll close the PR (mostly to keep everything organized) - but of course, you can always open a new one 😁

**Comment by carolstran** [comment]
👋 Closing this now, but feel free to reopen or open a new issue if you're interested in speaking in the future!

**Pull request closed without merging**
