### PR TITLE
Add talk proposal for TypeScript

### PR DESCRIPTION
**Pull request by sambou**

### CODE REVIEW

**Comment by rmehner** [comment]
Hey,

thank for for proposing a talk and sorry that it took a lil' longer to reply. Would you be open to give this talk in March, as we've planned this React/React-Native special for February for longer :)

**Comment by sambou** [comment]
Sure, sounds good

**Comment by rmehner** [comment]
Hey there, still up for March 17th? If so, I'd put you on the page :)

**Comment by sambou** [comment]
Yeah, looking forward to it :)

**Pull request merged**
