### PR TITLE
Talk proposal: Snapshot testing

### PR DESCRIPTION
**Pull request by alexbeletsky**
Hello, I'm Alex.

I want to share my experience with Snaphost testing with Berlin.js community. I won't be talking about Jest that much, but what to show the benefits of Snapshots that goes beyond the front-end applications.

### CODE REVIEW

**Comment by rmehner** [comment]
IIRC you're not based in Berlin, right? We have somewhat of a node special for April (given the upcoming Node 10 release) and have two very focussed talks. What other dates would work for you (BerlinJS is always on the third Thursday of the month)

**Comment by alexbeletsky** [comment]
Hey @rmehner - no, I'm in Berlin currently. 

Unfortunately next month I'm on vacation, so only June I guess.

**Comment by rmehner** [comment]
That's great, hope you enjoy the city :) Have a great vacation then, I'll put you into our list for June :)

**Comment by rmehner** [comment]
Are you up for next week's meetup? :)

**Comment by alexbeletsky** [comment]
@rmehner next Thursday, right? I'm in :)

**Comment by rmehner** [comment]
Yep! Cool, will put you on the website :)

**Pull request closed without merging**
