### PR TITLE
Feel the Glimmer

### PR DESCRIPTION
**Pull request by marcoow**
I submitted this before and had to retract bun on Jan 18th (I think that should be the correct date?) I'll be able to make it 🤞

### CODE REVIEW

**Comment by marcoow** [comment]
Hey 👋 Is this something you'd still be interested in? I'm trying to plan some other things in Berlin around that and ideally I could finalize all of that this week so would be awesome to know if I'll be giving this talk on the 18th.

**Comment by rmehner** [comment]
Hey hey, sorry for letting you wait. We've been a bit into hibernation for the time :)

Anyway, January is actually reserved for our framework special, so for this talk we're aiming more for February or later. Does that fit for you?

**Comment by marcoow** [comment]
No worries, guess the week before christmas is not a great time for planning things like this ;)

So yeah, February works as well, thanks for the update!

**Comment by rmehner** [comment]
@marcoow hey there :) How's your schedule for July? Would July 19th work for you? If not, do you think someone from your team in Berlin would be able to give this talk?

Sorry for all the delays, we've got a proper Trello board now where we sort all the talks, so we don't forget anyone :)

**Comment by marcoow** [comment]
Hey 👋 I won't actually be able to give the talk in the next few months :( I'm closing this for now but will re-submit once I'll be able to actually give it. Would be great to eventually come to Berlin and do it :)

**Comment by rmehner** [comment]
Hey Marco, hope everything is fine. Will be great to have you eventually. Feel free to hit us up anytime.

**Comment by marcoow** [comment]
Yeah, all good, thanks - just the baby keeps me busy ;)

**Pull request closed without merging**
