### PR TITLE
Add talk proposal for Catberry.js

### PR DESCRIPTION
**Pull request by rdner**

### CODE REVIEW

**Comment by rmehner** [comment]
Hi there,

thanks for proposing a talk and sorry for the late reply. We planned to have this React/React-Native special we've talked about during our January meetup (and which has been planned since end of last year). Would you be open to give this talk in March?

**Comment by rdner** [comment]
Hi @rmehner,

Thanks for replying on this.

Yeah, I've been to January's meetup and heard about it, but I thought if there is no announce on the website maybe you change your mind, therefore I created the PR :).

March works for me as well. Let's move it there then.

**Comment by rmehner** [comment]
Hey there, does March 17th still work for you? If so, I'd merge this and put you on the page :)

**Comment by rdner** [comment]
@rmehner it does. Sounds perfect, thanks! :)

**Pull request merged**
