### PR TITLE
Talk proposal: Cypress: e2e testing for Web in 2019!

### PR DESCRIPTION
**Pull request by destromas1**

### CODE REVIEW

**Comment by carolstran** [comment]
Hey @destromas1 👋 Thanks for submitting! According to your GitHub profile, you're not located in Berlin. Is that correct? And if so, would you need travel and/or accommodation covered?

**Comment by carolstran** [comment]
Also are you a first-time speaker?

**Comment by destromas1** [comment]
Hey @carolstran,
Thanks a lot!
I live in berlin.
I was a speaker at https://www.meetup.com/ReactJS-and-React-Native-Berlin/events/248568695/  and https://www.meetup.com/ReactJS-and-React-Native-Berlin/events/242532278/ in Berlin.
I also attended few coding bootcamps as a Coach in Berlin.
Other than that, I attended a few meetups/confs as a Speaker in Bangladesh.

**Comment by carolstran** [comment]
Great good to know, thanks @destromas1 🌟 We'll be in touch again once we have a better idea of when you'd fit in.

**Comment by destromas1** [comment]
@carolstran , you're welcome! sure 👍 please let me know!

**Comment by carolstran** [comment]
👋 @destromas1, quick question for you. Is there any chance that you'd be open to delivering a 5-10 minute version of your talk?

If not, no worries - we can keep you on the regular waitlist. Just trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by destromas1** [comment]
@carolstran ,
I can do 10 minutes. But 15-20 mins would be better.
Also, How long it will take to give me a slot on the regular list?

**Comment by carolstran** [comment]
Depends on how everyone else replies 😁 

Let me get the other responses and then I'll let you know!

**Comment by destromas1** [comment]
@carolstran , Sure 👍 
Also, I would like to be on the regular list if possible :)

**Comment by carolstran** [comment]
Ok then I'll remove the ⚡️ label and get back to you when we have a slot! Looking at the current list, I'm guessing it'll be either November 2019 or Q1 2020. The November meetup will be on Thursday, Nov 21 if you're available or the dates for Q1 are January 16, February 20 and March 19 if any of those already look good to you 😊

**Comment by destromas1** [comment]
@carolstran ,
I can probably do 10 minutes now and then do another one( different topic ) on the regular list when it's available in November or Q1'2020 ? :blush: 
Wdyt?

**Comment by carolstran** [comment]
Honestly, we have so many talks on the waitlist that I don't think it'll be possible for one person to do two talks in that short of a timeframe 😞 Sorry! So I would say you should choose one (either 10 minute or full-length) and plan for that. The main difference is just we might be able to schedule the 10-minute talk sooner (or we might turn the November meetup into only lightning talks - still tbd).

**Comment by destromas1** [comment]
@carolstran ,
It's okay 😊 👍 I would like to be on the regular list. Please keep me to the regular one 👋

**Comment by carolstran** [comment]
Hey hey @destromas1 👋 You're at the top of our waitlist (finally ugh sorry it takes so long). Our 2019 meetup lineups are full, but all of our 2020 meetups still have slots. The Q1 dates are January 16, February 20 and March 19. Let us know if any of those work for you 😁

**Comment by destromas1** [comment]
Hey @carolstran  👋 
it's okay :)
I think January is fine for me 👍 
BTW, in the mean time, I talked at 2 events in Berlin -
https://www.meetup.com/Node-js-Meetup-Berlin/events/262650013/
https://www.meetup.com/ReactJS-and-React-Native-Berlin/events/252502488/

**Comment by carolstran** [comment]
Great! Consider yourself confirmed for January and we'll check in again later this year 😁

**Comment by destromas1** [comment]
Awesome! Thanks! 👍 😊

**Comment by carolstran** [comment]
Hey hey @destromas1, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (Thursday, January 16) 🎉 And if yes, then please let me know if you want to make any changes to your title/abstract before we add it to the website 🥂

**Comment by destromas1** [comment]
Hey @carolstran ,
I will join 😊:tada: 
Title -
`100% test coverage is not enough...`

Abstract  -
Being honest, we(the developers), had a hard time testing our web applications, specially when we wanted to do e2e testing. Complex environment? flaky tests? slow and boring? A lot of manual time waits?  We all faced some or all of them. Right?
Let's see how we can test our code, not our patience.

**Comment by carolstran** [comment]
👋 @destromas1, we added your talk to [our website](https://berlinjs.org/) and [tweeted about it](https://twitter.com/berlinjs/status/1215196087532818433?s=20). Just so you know, @SaraVieira will be the only organizer at the meetup on Thursday, so please find her and check-in when you arrive 😊

Co.up has an assortment of doggles, etc. - but if you need anything specific for your talk, please just let us know. Looking forward to it 🎉

**Comment by destromas1** [comment]
Hi @carolstran 👋 
Nice, thanks a lot!
I will find @SaraVieira and check-in 👍

**Comment by carolstran** [comment]
👋 @destromas1, thank you again for giving a talk at our January meetup! I was sad to miss it, but it seems like it went very well. I'll close the PR now, but always feel free to reach out if you have any feedback 😊

**Comment by destromas1** [comment]
@carolstran Hi 👋
I hope, the audience liked it 😊

I want to give a lightning talk ⚡️at one of the upcoming meetups. 5 minutes would be enough for me!
I am working on a CLI called `create-awesome-package`  .
https://dev.to/destrodevshow/released-a-cli-create-awesome-package-to-bootstrap-your-js-ts-package-2ole
It's like create-react-app but for building packages 📦

Do you suggest to send a new PR for this?

**Pull request closed without merging**
