### PR TITLE
talk proposal: node.app

### PR DESCRIPTION
**Pull request by srijs**
Hi!

I'd like to propose a talk for the March meetup of berlin.js.

The description is a bit fancy, let me know if you want it more straight-forward ;)

Cheers!

### CODE REVIEW

**Comment by rmehner** [comment]
That's pretty cool, only thing: It's in the wrong div, it has to be in the div below (`<div class="three-cols clearfix">`)

We'll have you in march than, totally looking forward to this :)

**Comment by srijs** [comment]
Cool!

Uh, yeah, my bad ;) Fixed that.

**Comment by rmehner** [comment]
@localheinz this was supposed to be merged in March. Had to revert the merge and we have to re-revert once it's March :)

**Comment by localheinz** [comment]
@rmehner Let me invite you to a beer next time!

**Comment by rmehner** [comment]
Don't worry, stuff happens :)

**Comment by srijs** [comment]
@rmehner just pinging to remind you of the existence of this PR ;)

**Comment by rmehner** [comment]
Will properly merge that as soon as I'm home again :)

**Pull request merged**
