### PR TITLE
html api talk

### PR DESCRIPTION
**Pull request by illume**

### CODE REVIEW

**Comment by rmehner** [comment]
\o/ Thank you and welcome :)

**Comment by illume** [comment]
Thanks @rmehner :)

**Comment by rmehner** [comment]
Hey there, would you be up to give this talk in March?

**Comment by illume** [comment]
Hey hey. I'd love to... but I'm not sure if I'll be in Berlin then. Will find out in a few days, and get back to you. Hope that's ok?

I can't believe the lights came back on! haha.

**Comment by rmehner** [comment]
Yep, that's okay. We have someone else waiting, but that person also could give his talk in April then :) Let us know what suits you best.

**Comment by illume** [comment]
Yeah, boohoo... I can't make it this month. Hopefully next time! Will try and drop in for the April coworking day too.

**Comment by rmehner** [comment]
No worries, I've noted you down for April, see you then!

**Pull request merged**
