### PR TITLE
Talk proposal about web workers

### PR DESCRIPTION
**Pull request by PragTob**
**Do not merge... see comment below... calendar collision :-/**
- I don't mention my go engine since it's not ready yet but I will give my
  best (oh yeah I'm building a go engine with web workers)
- I'd also like to touch upon the similarities to the Actor pattern if that's
  interesting for you and if I got enough time in the talk

Feedback very welcome.

edit: yes I finally submitted it ;-)

### CODE REVIEW

**Comment by PragTob** [comment]
_takes a look at the calendar_
Damn it Boysetsfire concert is on the 20th of june starting 20:00...
Ok sorry and my bad... :-/ Shall I leave this PR open for July? Or resubmit then?

**Comment by rmehner** [comment]
Yup, just leave it open. We'll remember that and will have you in July then.

**Comment by rmehner** [comment]
Preparing the July meetup: Is this still valid? Date would be July 18th. Thank you :)

**Comment by PragTob** [comment]
Yes it totally is valid! Would probably have to change the position of the talk but otherwise it should be good :-D

**Comment by rmehner** [comment]
Exact position of the talk during the evening is always a bit spontaneous, because sometimes people show up late etc. But we can talk about your preference then :)

Thank you!

**Pull request merged**
