### PR TITLE
Proposal: A/B Testing talk

### PR DESCRIPTION
**Pull request by brianegan**
Hello! My name is Brian Egan and I'm a Front End Engineer at SoundCloud. Tiffany asked us if we'd like to participate in the next BerlinJS.

If you'd like, I'd be happy to give a talk on A/B testing.

Thanks for your consideration :)

### CODE REVIEW

**Comment by theophani** [comment]
Yes please!

**Comment by brianegan** [comment]
Hey all, small nudge: final yay / nay to this topic? It takes me a bit of time to prepare a quality presentation and I don't want to jump into that process until I have confirmation.

**Comment by rmehner** [comment]
Sorry, was lost in my todo :)

**Comment by rmehner** [comment]
Merged & confirmed. Thank you very much!

**Comment by brianegan** [comment]
Cool, thank you!

**Pull request merged**
