### PR TITLE
Past, Present and Future of JavaScript Frameworks.

### PR DESCRIPTION
**Pull request by flpvsk**
A 15-minutes long talk I [gave earlier in Russian](https://yandex.ru/yac2014/program/frontend/#frameworks). The main purpose is to start a discussion on 'What JavaScript frameworks of the future should look like?'

### CODE REVIEW

**Comment by rmehner** [comment]
This is for December, right? Would you be up to give this talk in January? We're not sure if there will be a December meetup, gonna ask people about that during the November meetup, because usually the December one is pretty late and everyone is doing christmas things

**Comment by flpvsk** [comment]
@rmehner sure, both December and January work for me.

**Comment by rmehner** [comment]
Totally forgot about this one, would you be open to do that for this February meetup as well?

**Comment by rmehner** [comment]
And sorry for overlooking this one.

**Comment by flpvsk** [comment]
No problem!
Unfortunately, I won't be able to attend the meetup for a couple of month. I'll send a new PR once things change.

**Pull request closed without merging**
