### PR TITLE
HTML Email in the React World

### PR DESCRIPTION
**Pull request by Rendez**
At ResearchGate in Berlin, we send out plenty of HTML emails per day, over a dozen different layouts.

I'll show you how we're getting a handle of it with React (as a rendering engine), and how is given us a better and more consistent layout system. On top of React emails we set out to create a great developer experience for our teams.

I have a draft and a presentation that I'm cooking at the moment, I'll show how React works with the particularities of HTML4 for email rendering, how it can help provide warnings for compatibility issues across email clients, and how we setup our email dev environment to craft predictable layout results with HMR, and litmus previews.

### CODE REVIEW

**Comment by rmehner** [comment]
That sounds very interesting indeed! Would you also be able to give that talk in April, since we have two talks for March that are just waiting for confirmation.

**Comment by Rendez** [comment]
@rmehner that would actually give me a bit of extra time to prepare. April it is :)

**Comment by rmehner** [comment]
@Rendez noted you down for April then, looking forward! Thanks for submitting.

**Comment by Rendez** [comment]
@rmehner are you guys updating the calendar for April?

**Comment by rmehner** [comment]
Yes, we're in the middle of planning a special event for pre-JSConf, and we need to decide if we make a regular April meetup and the special one or just merge to one bigger one. Will decide on the weekend and keep you posted.

**Comment by rmehner** [comment]
Welcome to our April line up :)

**Pull request merged**
